# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1.0.2
      with:
      # GNU Embedded Toolchain for Arm release name, in the V-YYYY-qZ format (e.g. "9-2019-q4")
      release: '7-2018-q2'


    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        cp template/Makefile.posix.template template/Makefile.posix
        sed -i "s/\/usr\/local/\/tmp/g" template/Makefile.posix
        sed -i "s/\/usr\/local/\/tmp/g" template/Makefile.posix
        cd keyboard
        make -j
        cd ../
